// server.js
const express = require('express');
const cors = require('cors');
const { GoogleGenAI } = require('@google/genai');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware to process cross-origin data traffic and parse JSON strings
app.use(cors());
app.use(express.json());

// Initialize the Google Gen AI SDK connector client mapping

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// ⚡ THE REAL LIVE AI INTERFACE ROUTE
app.post('/api/chat', async (req, res) => {
    try {
        const { message } = req.body;
        if (!message) {
            return res.status(400).json({ error: "Message input cannot be blank." });
        }

        console.log(`📡 Forwarding message to Gemini brain: "${message}"`);

        // Send the prompt straight to the high-speed gemini-2.5-flash model
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: message,
        });

        // Pull the text response generated by Gemini
        const aiReplyText = response.text;

        // Send it right back down to your website layout screen
        res.json({ reply: aiReplyText });

    } catch (error) {
        console.error("❌ Gemini API Gateway Error:", error);
        res.status(500).json({ 
            error: "The backend server encountered an issue connecting to the AI brain.",
            details: error.message 
        });
    }
});

app.listen(PORT, () => {
    console.log(`🚀 StudyBuddy Server spinning up seamlessly on http://localhost:${PORT}`);
});